import { Product, BuilderPart, Enquiry } from './types';

export const CATEGORIES = [
  'Laptops',
  'Desktops',
  'CCTV Systems',
  'Components',
  'Printers',
  'Networking',
];

export const BRANDS = [
  'ASUS',
  'DELL ALIENWARE',
  'HP OMEN',
  'LENOVO LEGION',
  'APPLE MACBOOK',
  'RAZER BLADE',
  'CP PLUS',
  'HIKVISION',
  'EPSON',
  'CANON',
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'asus-rog-strix-g16',
    name: 'ASUS ROG Strix G16',
    brand: 'ASUS',
    category: 'Laptops',
    specs: 'i7 13th Gen / RTX 4060 / 16GB DDR5 / 1TB SSD',
    price: 124999,
    originalPrice: 139999,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDNfA7LcRdCTKaWI9Fw7sTlQT5o4umwUsfAUqqgximm6rx68VR3hbpgV-Ik9g26-tlYOVNGUvADvOIy7pl6UdQyj8YZr0jFPXU95rvkKRcsiA7VdtcqLpcRapmTlxsTLLCpWoI478PLUGq-5qLCXgPBWHXfyk6NZhoEfFpnzDxYanpwk2pbuxvaxxXz1Sdnpjhe1VxDn_Sc-Fww3rnal5Vj1cGttmsenqzIndavRj3NeovsLXsyiZFSHnIul9JZieJ9mKB1u1s309o',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCfEWeCVAY79FhPFCj_scSQUtTJKsF7bMVchs5JSOGNa_iAIMKJnPt5xQQjHfGWudU6AygC5aNUZOgdPHpRPlxWrJzOFnfWl0798papmjXshCbCCDADzsMUQEtn8CJo1KujVzLH5TnpWBEM_Wi3DM_L7bPPT7trVNO4IjTLerAgj85UkXpzzg55KJsammWpAfLWBU2AA2noA0yNIVJmVUEYucEYZ3vgh9Xz_BJi9cbuJ-tOV3bRmATEuoYIq1fbK3x3mqHbZ0PXMe8',
    ],
    inStock: true,
    isNew: true,
    warranty: '1 Year Brand Warranty',
    processor: 'Intel Core i7 13th Gen 13650HX',
    memory: '16GB DDR5 4800MHz',
    storage: '1TB NVMe PCIe 4.0 SSD',
    display: '16" WUXGA FHD+ 165Hz IPS Display',
    keyFeatures: [
      'NVIDIA GeForce RTX 4060 GPU with MUX Switch',
      'ROG Intelligent Cooling with Liquid Metal',
      'Aura Sync RGB Backlit Keyboard',
      'Dolby Vision & Dolby Atmos Audio Support',
    ],
    description: 'ASUS ROG Strix G16 is precision engineered for high-frame-rate competitive gaming. Packed with a 13th Gen Intel Core i7 processor and an RTX 4060 GPU, this machine effortlessly conquers extreme gaming workloads, rendering buttery smooth visuals on its lightning-fast 165Hz IPS display.',
  },
  {
    id: 'vip-master-workstation',
    name: 'VIP Master Workstation',
    brand: 'ASUS',
    category: 'Desktops',
    specs: 'Ryzen 9 7900X / 64GB DDR5 / RTX 4080 / 2TB SSD',
    price: 245000,
    originalPrice: 269000,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDOJkIk0GRdEUxYFPyytAMu7xfuN97j2f0YVqSHsc7U-wcpT7WqX23lTCnNdpMYb4IsyVGbQl-eZgZyHThs37jQsA0Ryyntiyo8TIaUm82akevW524X8GSpU5MaaNVJgnBAZA6BkqkvWpfMU6ebNKxM1oWDqR9ssZbgcd25XImgBGmxUdFg5aIkcCYcP_knjWkqIaN10QzySZ-sDEokW-XnFRmF7ovavqR3k-UU9j9pnSDVdhw1hCO2IyX-AebpynLh_eLijtu44Z0',
    inStock: true,
    isHot: true,
    warranty: '3 Years Comprehensive Warranty',
    processor: 'AMD Ryzen 9 7900X (12 Cores, 24 Threads)',
    memory: '64GB Dual Channel DDR5 5600MHz',
    storage: '2TB NVMe Gen4 High-Speed SSD',
    display: 'No Monitor Included (Supports up to 4x 4K Monitors)',
    keyFeatures: [
      'NVIDIA GeForce RTX 4080 16GB VRAM Graphics',
      'Premium 360mm Liquid AIO Liquid Cooling',
      '1000W 80+ Gold Fully Modular Power Supply',
      'Sleek white & silver high-airflow aluminum chassis',
    ],
    description: 'The VIP Master Workstation represents the absolute zenith of desktop performance. Tailored for software compilers, architects, 3D modelers, and elite content creators, this machine handles the most demanding professional render threads with stunning efficiency and whispering-quiet liquid cooling.',
  },
  {
    id: '34-curved-gaming-display',
    name: '34" Curved Gaming Display',
    brand: 'RAZER BLADE',
    category: 'Components',
    specs: '165Hz / 1ms Response / HDR 1000 / QHD Resolution',
    price: 48999,
    originalPrice: 55000,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCMBNLW8l894Xhy9UAlTL2OIIhpdRNQAlgk15MKYuwifc_KXOKt9ZGrU60rid6it-3myZun1f5Yu_GMiswO5GL_rHDNeNg2vMpD88kzfyVmw93Nksw2UU4d7xPJAfYEBUB5NT_jcI5wh8OQkFIs2oY0qk1XjwR-R7EdBm0eBvdU5blMMjAwDm-p0xgy_L2RrEr71DdDPkvl1fQ67W5GhexhEkLVexiaC30511Qw7SV32oMSID3VHvrAoQpvkSg_MVHgKzeB_Kd--mw',
    inStock: true,
    warranty: '3 Years Panel Warranty',
    processor: 'N/A',
    memory: 'N/A',
    storage: 'N/A',
    display: '34" UltraWide QHD (3440 x 1440) Curved IPS Panel',
    keyFeatures: [
      'Immersive 1500R curvature matching human eye field of view',
      'Vesa Certified DisplayHDR 1000 for breathtaking contrast',
      '99% DCI-P3 cinematic color spectrum',
      'Dual HDMI 2.1, DisplayPort 1.4, and USB-C inputs',
    ],
    description: 'Get fully immersed in high-fidelity worlds with this 34" Curved Gaming Monitor. Boasting HDR 1000 and a 165Hz refresh rate, it bridges screen boundaries to put you in the center of action or give you massive panoramic workspace for multi-tasking.',
  },
  {
    id: 'hp-envy-aio-27',
    name: 'HP Envy AIO 27',
    brand: 'HP OMEN',
    category: 'Desktops',
    specs: 'i9 13th Gen / 32GB RAM / 1TB SSD / 4K Display',
    price: 189999,
    originalPrice: 210000,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDvhG5_KisGuf7yUSzs0eFZnbGydngg_7FWNSPdNVr7M_S32zZfYpvIRDHYZo90l0c9-mfLqSo0MWuZhXQNKukHe0h2ovl-uoxYgDFcCeaisjhtvRJOt7Cw1R-4HXFugBiI4MdTMVVqlxfeNM_He8i2IsNN05KxZyxxu_D_SZDRP6D4XWf8NPGr0rNEQn4Pvv4HjYJsWJrllXfWh3_jG18iggy4Z_sTKx1imKqlsx4g_mQtHH-TP38aKTdcD23IYuqzvW7jTQQwnqo',
    inStock: true,
    warranty: '1 Year Brand Warranty',
    processor: 'Intel Core i9 13th Gen 13900T',
    memory: '32GB DDR5 RAM',
    storage: '1TB PCIe NVMe SSD',
    display: '27" UHD 4K (3840 x 2160) Edge-to-Edge IPS',
    keyFeatures: [
      'Detachable wireless-charging base built into stand',
      'Sleek minimalistic, all-in-one space-saving layout',
      'Integrated pop-up 5MP camera with privacy shutter',
      'Bang & Olufsen tuned quad speakers',
    ],
    description: 'Crafted for creators and home offices, the HP Envy All-in-One 27 pairs a magnificent 4K resolution screen with high-tier Intel Core i9 compute. Save space while retaining full desktop capabilities in a gorgeous workspace layout.',
  },
  {
    id: 'rog-strix-scar-18',
    name: 'ROG Strix SCAR 18',
    brand: 'ASUS',
    category: 'Laptops',
    specs: 'Intel Core i9 13th Gen, RTX 4090, 32GB DDR5, 2TB SSD',
    price: 349990,
    originalPrice: 389990,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCLDLy0fiEkqfcwActR3rjOj1kAfiBquBNOCFKNmoPLyPd2EaO45WdabEZCiA60EQXG6F75XBv_lYW_IPpGoGVGckuMB2brooVrjwqTkSUKTLY6_D7tyGdelsxTaSIrwSDiOF3iOOdPWyjwjEYJPiDCNoGske-GdINHhJsUqm8cjaRSom1f8NfluzepASqYfcWnniYPEqjOeoPMw-brZjrjza9cJCELlWrtvSVzFgjVIAPopuvqTXzxXc7QZ-pLcPFUP_KDp8EDo08',
    inStock: true,
    isNew: true,
    warranty: '2 Years Global Warranty',
    processor: 'Intel Core i9 13th Gen 13980HX',
    memory: '32GB DDR5 5600MHz Dual Channel',
    storage: '2TB PCIe Gen4 RAID 0 Performance SSD',
    display: '18" QHD+ ROG Nebula HDR 240Hz Mini-LED',
    keyFeatures: [
      'NVIDIA GeForce RTX 4090 Laptop GPU (175W Max TGP)',
      'Mini-LED Panel with 1100 Nits peak brightness',
      'Triple-Fan Thermal Technology with full-surround vents',
      'Customizable Armor Caps and per-key RGB lighting',
    ],
    description: 'ASUS ROG Strix SCAR 18 is the ultimate heavyweight powerhouse. Equipped with the absolute apex of mobile specs, the 24-core i9 CPU and 16GB RTX 4090 GPU deliver visual fidelity and rendering speeds matching elite desktop workstations on a mesmerizing 240Hz Mini-LED display.',
  },
  {
    id: 'alienware-m18-r1',
    name: 'Alienware m18 R1',
    brand: 'DELL ALIENWARE',
    category: 'Laptops',
    specs: 'Ryzen 9 7945HX, RTX 4080, 18-inch QHD+ 480Hz Display',
    price: 285990,
    originalPrice: 299990,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBYxVQ_ZbGWcsKPTaMOX9-2G5y8M1pO1b3Q1jWQ_ez4yuZDLAMW491gBNy2BMeh39HBZT4dbeWkXiXKy5W8CutViwzBo4gmEz2AtkBOFGxrYLt4o5HdMDH6Cld8eDnO2hvgva4hy7FZlEvOWwXnBxhoEc6A9ivpATOXMerpcg-P9MftXvLdVF3MHqMld7QfhDj-K1V0d5_tSPyUcOCtII82lUIEJHMVzgAA2izUg5s2emwelDUzxrUv2zCSw-JcS1KM1rQtXnFcZa4',
    inStock: true,
    isHot: true,
    warranty: '1 Year Premium Support Plus',
    processor: 'AMD Ryzen 9 7945HX (16 Cores, 32 Threads)',
    memory: '32GB DDR5 RAM 4800MHz',
    storage: '1TB M.2 PCIe NVMe Gen4 SSD',
    display: '18" QHD+ (2560x1600) 480Hz Refresh Rate',
    keyFeatures: [
      'Alienware Cryo-tech™ thermal cooling with Element 31 thermal interface',
      'CherryMX ultra-low profile mechanical keyboard',
      'Legend 3.0 premium aluminum architectural design',
      'Customizable AlienFX stadium loop RGB lighting',
    ],
    description: 'This Dell Alienware behemoth is built to shock and awe. Running AMD flagship Ryzen 9 processor with RTX 4080 graphics, it unleashes raw rendering and gaming throughput on the world-first 18-inch 480Hz QHD display. Styled with beautiful dark metallics.',
  },
  {
    id: 'legion-pro-7i-gen-8',
    name: 'Legion Pro 7i Gen 8',
    brand: 'LENOVO LEGION',
    category: 'Laptops',
    specs: 'i9-13900HX, RTX 4080, 32GB RAM, 1TB NVMe Gen4 SSD',
    price: 245990,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuABHAIE9GVj8AguepHUqzcB34-bJ6GWsnDVGJTGfUDJoyGXaVW2VaNyR0RL9kpz7ZHk6L04WAA0Klrxze0GQuTqfI2761q2tEhulGEjpyBu6B_hBgqXB374BhY3vAgVQuNsjnHAAUWwCO1oCzUE9HtUor4MkyWC-ncc7QDlaP1CSB5o1W6_PfSrK2VOseuiG1xI3BkPWhGuWxjT87P8l9wHY8Mm1deGK9mVF-OYFNRL9JWo-9Eeto_WWh8gNJ8_DKOcFxekRuW-tWU',
    inStock: true,
    warranty: '1 Year Legion Ultimate Support',
    processor: 'Intel Core i9 13th Gen 13900HX',
    memory: '32GB DDR5 (2x16GB) 5600MHz',
    storage: '1TB PCIe Gen4 NVMe M.2 SSD',
    display: '16" WQXGA 240Hz IPS Display with G-Sync',
    keyFeatures: [
      'Lenovo Legion AI Engine+ powered by LA2-Q AI chip',
      'Coldfront 5.0 hybrid liquid thermal cooling with vapor chamber',
      'Eco-friendly sustainable aluminum frame',
      'Per-key RGB backlit keyboard',
    ],
    description: 'The Lenovo Legion Pro 7i Gen 8 balances brutal gaming frame-rates with sleek, corporate understatement. Its high-resolution 16" IPS display is highly color-accurate, making it perfect for engineers who game after hours.',
  },
  {
    id: 'omen-transcend-16',
    name: 'OMEN Transcend 16',
    brand: 'HP OMEN',
    category: 'Laptops',
    specs: 'i7-13700HX, RTX 4070, 16GB, 1TB SSD, 240Hz OLED',
    price: 172500,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD80pr174yozOMGfb3Ji34ztZGV8_wpJqV7IuZ6-7v_qbF_kE7Fbg1WUruru5Nax94QhLPLeYzqvZzMsgyUt8zm_iMHADs6RetE7rCJ0VnLcAxCcIO5Y0kz1j-JsAU1IxZ4ysvHeBOaaGZBWiZ6Dfyvn4E2KZBqq10txzLoAoUudZg9s9yATr9K0fGhKLRblksUBQsWUsDsGVzUTV9-5HGEijpWm_oS7wQbjh8NrRsiRwTrEg9hVVqLCPnEHJStFDpMrhK4j6vyzec',
    inStock: true,
    warranty: '1 Year Onsite Warranty',
    processor: 'Intel Core i7 13th Gen 13700HX',
    memory: '16GB DDR5 4800MHz',
    storage: '1TB PCIe NVMe TLC M.2 SSD',
    display: '16" WQXGA 240Hz OLED Display (HDR 400)',
    keyFeatures: [
      'Breathtaking infinite contrast OLED panel',
      'Magnesium-aluminum hybrid ultra-light chassis',
      'Omen Tempest cooling architecture',
      'Dual speakers custom tuned by HyperX',
    ],
    description: 'The OMEN Transcend 16 is designed for digital creators who value portability and infinite contrast. Centered around a gorgeous 240Hz OLED display, this laptop brings rich depth to movies, edits, and gameplay alike, all in a chassis under 2.1kg.',
  },
  {
    id: 'macbook-pro-14-m3',
    name: 'MacBook Pro 14" M3',
    brand: 'APPLE MACBOOK',
    category: 'Laptops',
    specs: 'M3 Pro Chip, 11-core CPU, 14-core GPU, 18GB Memory, 512GB SSD',
    price: 199900,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAWyJbUKVDRSKP7iaiaQjBt4u-CLw5OZwZvXrOyK5Ayfj2_BcCRGGjZJX4_LyNy_cYj2UQAjYU1kQISQJS_YErlyFw6nAO5OK4nSsLREjGhNIFPyNWky9AaHktWs4Ucb6FkDAM21cQ8APv2QrzrH5JfeEloQGTgFub0c9tp03BneD43YuZ88W6g7QQjvJbFMoxw4pKBWndeOj5TTWqr_lFDrfdpZgvrbeJ0o745p9bspSQYMvgAiUHXAa_AykbGUg6954Q3gBIHPyw',
    inStock: true,
    warranty: '1 Year Apple International Warranty',
    processor: 'Apple M3 Pro Chip with 11-core CPU',
    memory: '18GB Unified Memory',
    storage: '512GB Superfast Apple SSD',
    display: '14.2" Liquid Retina XDR display (120Hz ProMotion)',
    keyFeatures: [
      'Next-level hardware accelerated ray tracing on M3 GPU',
      'Incredible battery life up to 18 hours',
      'Studio-quality six-speaker sound system with Spatial Audio',
      'Uncompromising peak brightness of 1600 nits on HDR content',
    ],
    description: 'The MacBook Pro 14" with Apple M3 Pro chip delivers staggering compile, render, and editing performance without needing a wall plug. Encased in a beautiful space black anodized finish, it is the benchmark laptop for modern creators.',
  },
  {
    id: 'razer-blade-16',
    name: 'Razer Blade 16',
    brand: 'RAZER BLADE',
    category: 'Laptops',
    specs: 'i9-13950HX, RTX 4090, 32GB RAM, 2TB SSD, Mini-LED Display',
    price: 425000,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDrFPgbpsIIPk1t3Fguv-sNjwLOwLD89DIpeDEmWhZO8O9gvk1Z3OjB89TSAkmBtONYD02S4aO0ZyePL1pMhspDCUVhbd31rvzVNsjC6qWaTNI1aEURWbtsszxNoj5dOmapJOCOxNwcNxvSO6SoAuli9P1K2KVPqbbbOMneb7MLODDqdzTcRyVgT3_kRXU1PFvL8LGvXK0ok9gqJWrA_D9VP80hI-CQZ2JrghRN-gnZx6EmpCxIH6raPexecIoy5RbBmpHWlrmci_I',
    inStock: true,
    warranty: '1 Year Brand Warranty',
    processor: 'Intel Core i9 13th Gen 13950HX',
    memory: '32GB DDR5 5600MHz RAM',
    storage: '2TB PCIe Gen4 Performance SSD',
    display: '16" Dual-Mode Mini-LED (UHD 120Hz / FHD 240Hz)',
    keyFeatures: [
      'Dual-Mode screen capable of switching native resolutions on the fly',
      'Chambered vapor cooling block for maximum graphics thermal efficiency',
      'CNC milled solid T6 aircraft-grade aluminum unibody design',
      'Razer Chroma per-key RGB backlight with Synapse 3 software',
    ],
    description: 'Known as the ultimate luxury gaming notebook, the Razer Blade 16 provides unparalleled power-to-volume. Combining a monstrous Core i9 with desktop-class RTX 4090 graphics, it is CNC-machined to perfection for elite portability.',
  },
  {
    id: 'asus-vivobook-15',
    name: 'ASUS Vivobook 15',
    brand: 'ASUS',
    category: 'Laptops',
    specs: 'i5 13th Gen / 16GB / 512GB SSD',
    price: 54999,
    originalPrice: 68000,
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA5fj8GxYac8nkq58q7f3PB9PbPHXwAst-iFt_cjKCubvxUmBvC4EFvSVQ6iB1ZiQYMsMhqq6Amz82GRrWry8Y-XJFicNu9PlmQhQSQbuehb3L_Y83XVrYf4QMNLDZ5Ns1a9NEOMgyEhCU3DmcA-3QJe4ZxOnAHVOxhP7E0x2qGVTQIRJTq7maN_HL9scWwLhAhxdiWJDsgXQXWIT8eG77SBmVF-IIdP5gfB35q8siXWqzXwh6rS-SU7sXK6oc6OW0la24n-I4KeD4',
    images: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuCZoiJOyXKUxr6k0WzK_LnnTS87iqUqOIW55Vub6QnPBdBFo_S7PTBsqS4-L9Dt6DVbaCVwpzQDpjZEjxszsZRgCqvwVML5YULPxCxO3mpwxjAf5gt61hosyUyzf43qT4oaciGgauW5BN4ijxGseYblyy_bjaNawCxZmke-JnXGJIbfH2rVUbbCbUAtka9R1kz-j8f07-RDhfIrE5TVCejmqJ4RQwtpLRhnUH4z24BTanW4vuF_bSVqOM2FeeDJeHfroFPpqQPLRTY',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAu9My5TVWQQO97REMLTLScIzOdyvIG4FyQQsnWczcmq0dZiXxZUP7P6xpMrfiZCpvpgMWC5pLBTJVyHudgh2j0nKd96R3KTk_8tyQQ214FznDaszToj9cFy50wCSTon8JNJVay-KI-478OOIEoNWHLUvq9Fry18H60LByjB-hmnXTFC1VcE47byoy3FjAq5ZqchgIL5YRfoXnfrSaFDPMfQrugoC5tfs5QeXaTxZRxXwG8xdBPanpL3JVZ7H5uX_H39bmNuv3kBpg',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDLYzeuuD4kJTem8gecGejm96fPbqEpI3vvHHx_X81ivjvp3OmcxBzULCP_FQXgX3Y-ENIKDFkjZvVC_NnRkHNqWkZyvq5oY9xp6qy_DA86IxxTvXi1DDJW8RMxaUXyg4e5rcHkLnihCujVPtf6XUEQJF9G1KpAcvev_dggm0xyQ30ls-9R2e0UBZruUfOkXD40dP4LQqt7n6nMcjV3bGfAkxkBCvr4mRMLk0C2uVT9Mp23IZ-GYVEWobk-NJ2QwlKD7y4cjIwDxi0',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuAv9zqnT0zcoRe7MN2438JzB_K8DWO9Xrz51mY-SfQd0B3pz0CY662O3IW5ILTr4-CylzQ3bqH2GQICTm_ZErpuT26jZG5wZ_1woLCHYb7ovN4Fd7wZoWzpeXyMSVG8qO16zbb3VNqOVMNni3C5gHn49MAOdNDcJHmKBxoM337xSEdefuKT8C_QX_wapK0YUP-UdJd153JBxDD-x1lBlU_ZZBTlClwX0IDN6JQSsF3IH_HVXw7zt5OZ9adrwvHScRVabCEULr-r96w',
    ],
    inStock: true,
    isNew: true,
    warranty: '1 Year Brand Warranty',
    processor: 'Intel Core i5 13th Gen 1335U',
    memory: '16GB DDR4 RAM',
    storage: '512GB NVMe SSD',
    display: '15.6" FHD (1920x1080) IPS Anti-glare Display',
    keyFeatures: [
      'Windows 11 Home & Student 2021 pre-installed for immediate productivity.',
      'Office Home & Student 2021 lifetime validity included.',
      'FINGERPRINT reader for fast, secure, password-less logins.',
      'Durable 180° lay-flat hinge and physical webcam privacy shield.',
    ],
    description: 'The ASUS Vivobook 15 is your perfect daily companion, ready to make short work of your agenda, whether it\'s office or personal, presentations or play. For demanding workloads, the latest 13th Gen Intel Core i5 processor is significantly faster than the previous generation. And with 16 GB of fast memory and 512 GB of speedy SSD storage, there\'s plenty of power in reserve when things get tough. Designed for long-lasting performance, this laptop features a durable 180° lay-flat hinge and a physical webcam shield for instant privacy. The sleek chassis is not only stylish but also rigorous military-grade tested for durability, ensuring your hardware remains the hero of your experience for years to come.',
  },
  {
    id: 'hikvision-smart-guard-8ch',
    name: 'Hikvision Smart Guard 8-Ch CCTV',
    brand: 'HIKVISION',
    category: 'CCTV Systems',
    specs: '8 Dome Cameras / 4MP UltraHD / 2TB Storage / Smart AI Alert',
    price: 24999,
    originalPrice: 29999,
    image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=500&auto=format&fit=crop&q=60',
    inStock: true,
    isNew: true,
    warranty: '2 Years Manufacturer Warranty',
    processor: 'Embedded Linux OS Controller',
    memory: 'N/A',
    storage: '2TB Surveillance Grade HDD',
    display: 'HDMI & VGA Output supported',
    keyFeatures: [
      '4MP QHD Crystal Clear Recording Day & Night',
      'AI Intrusion Detection & Human Classification Alerts',
      'IP67 Weatherproof metal casings for robust outdoor use',
      'Centralized 2TB Seagate SkyHawk Surveillance HDD included'
    ],
    description: 'High-performance commercial surveillance system featuring 8 smart IP cameras. Built-in AI deep learning detects human bodies and vehicles, filtering out false alerts from trees or rain to secure your facility.'
  },
  {
    id: 'cpplus-quad-shield-4ch',
    name: 'CP PLUS Quad Shield Pro',
    brand: 'CP PLUS',
    category: 'CCTV Systems',
    specs: '4 Dome Cameras / 2MP Full HD / 1TB Storage / Mobile Live View',
    price: 14500,
    originalPrice: 17999,
    image: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=500&auto=format&fit=crop&q=60',
    inStock: true,
    isHot: true,
    warranty: '1 Year Brand Warranty',
    processor: 'Quad Core Network SoC',
    memory: 'N/A',
    storage: '1TB Surveillance Grade HDD',
    display: 'VGA / HDMI Output up to 1080p',
    keyFeatures: [
      'Full HD 1080p Resolution with Wide-angle coverage',
      'Instant motion alerts sent to your mobile device via app',
      'H.265+ Compression for up to 50% extra storage saving',
      'Robust night vision IR distance up to 20 meters'
    ],
    description: 'Perfect for homes and small retail shops, the CP PLUS Quad Shield offers 4-channel security recording. Fast plug-and-play setup coupled with an intuitive mobile app lets you inspect live feeds from anywhere.'
  },
  {
    id: 'epson-ecotank-l3250',
    name: 'Epson EcoTank L3250 Printer',
    brand: 'EPSON',
    category: 'Printers',
    specs: 'InkTank All-in-One / WiFi / Color / Borderless Printing',
    price: 15499,
    originalPrice: 17999,
    image: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=500&auto=format&fit=crop&q=60',
    inStock: true,
    isNew: true,
    warranty: '1 Year or 30,000 pages Onsite Warranty',
    processor: 'Epson Heat-Free MicroPiezo Tech',
    memory: 'N/A',
    storage: 'N/A',
    display: 'Control Panel Buttons / LED Status Indicators',
    keyFeatures: [
      'High-capacity spill-free ink bottles for ultra-low print costs',
      'Wireless printing via Epson Smart Panel App & WiFi Direct',
      'All-in-One capabilities: Print, Copy, and Scan with ease',
      'Fast print speeds up to 10 ipm for black, 5.0 ipm for color'
    ],
    description: 'The Epson EcoTank L3250 delivers highly economical printing solutions. Featuring high-yield ink bottles that print thousands of pages before needing refills, it is perfect for micro-offices and busy school setups requiring low-overhead color output.'
  },
  {
    id: 'canon-imageclass-lbp2900b',
    name: 'Canon imageCLASS LBP2900B',
    brand: 'CANON',
    category: 'Printers',
    specs: 'Monochrome Laser / A4 / 12 ppm / High-yield Toner',
    price: 18500,
    originalPrice: 19999,
    image: 'https://images.unsplash.com/photo-1612815154858-60aa4c59eaa6?w=500&auto=format&fit=crop&q=60',
    inStock: true,
    isHot: true,
    warranty: '1 Year Canon India Warranty',
    processor: 'Canon CAPT 2.1 Processing Engine',
    memory: '2MB Onboard SDRAM',
    storage: 'N/A',
    display: 'LED operation indicators',
    keyFeatures: [
      'Professional monochrome laser printing at high speeds',
      'Robust design built for continuous office printing workloads',
      'Legendary Canon Cartridge 303 for pristine crisp black text',
      'Instant-to-print warm-up technology with low energy draw'
    ],
    description: 'The Canon imageCLASS LBP2900B is a legendary heavy-duty laser printer known for its unmatched stability and long-term service. Prints black A4 text docs with high contrast, making it an absolute staple for billing desks and reception counters.'
  }
];

export const INITIAL_ENQUIRIES: Enquiry[] = [
  {
    id: 'enq-1',
    name: 'John Doe',
    email: 'john.doe@gmail.com',
    phone: '9876543210',
    type: 'Build',
    subject: 'Extreme Gaming PC Quote',
    message: 'Looking for a custom liquid-cooled build with RTX 4090 and Ryzen 7 7800X3D. Can you supply custom white cables?',
    status: 'High Priority',
    date: 'Oct 24, 2024',
  },
  {
    id: 'enq-2',
    name: 'Sarah Miller',
    email: 'sarah.m@gmail.com',
    phone: '9821334455',
    type: 'Repair',
    subject: 'Liquid Cooling Leak',
    message: 'My current AIO cooler has started making noise and leaking. I need an urgent checkup and replacement before it damages my GPU.',
    status: 'Urgent',
    date: 'Oct 24, 2024',
  },
  {
    id: 'enq-3',
    name: 'Robert King',
    email: 'r.king@yahoo.com',
    phone: '9543112233',
    type: 'Upgrade',
    subject: 'RTX 4090 Stock Availability',
    message: 'When are the ROG Strix 4090 cards coming back to stock? I have my desktop ready to fit one.',
    status: 'General',
    date: 'Oct 23, 2024',
  },
  {
    id: 'enq-4',
    name: 'Amy Lee',
    email: 'amy.l@corporate.com',
    phone: '9112223344',
    type: 'Bulk Purchase',
    subject: 'Corporate Office Setup (12x)',
    message: 'Requesting a quote for 12 custom workspace desktops and monitor setups for our design agency. Needs powerful CPUs and fast storage.',
    status: 'Bulk Order',
    date: 'Oct 22, 2024',
  },
];

export const BUILDER_PARTS: BuilderPart[] = [
  // CPUs
  { id: 'cpu-1', name: 'Intel Core i9-14900K', category: 'CPU', brand: 'Intel', price: 49999, specs: '24 Cores / 32 Threads / up to 6.0 GHz' },
  { id: 'cpu-2', name: 'AMD Ryzen 7 7800X3D', category: 'CPU', brand: 'AMD', price: 38500, specs: '8 Cores / 16 Threads / 3D V-Cache' },
  { id: 'cpu-3', name: 'Intel Core i7-13700K', category: 'CPU', brand: 'Intel', price: 34200, specs: '16 Cores / 24 Threads / up to 5.4 GHz' },
  { id: 'cpu-4', name: 'AMD Ryzen 5 7600X', category: 'CPU', brand: 'AMD', price: 21900, specs: '6 Cores / 12 Threads / up to 5.3 GHz' },

  // GPUs
  { id: 'gpu-1', name: 'ASUS ROG Strix RTX 4090 24GB', category: 'GPU', brand: 'ASUS', price: 189900, specs: '24GB GDDR6X / DLSS 3.0 / Aura Sync' },
  { id: 'gpu-2', name: 'NVIDIA GeForce RTX 4080 Super', category: 'GPU', brand: 'NVIDIA', price: 105000, specs: '16GB GDDR6X / Ray Tracing Overdrive' },
  { id: 'gpu-3', name: 'ZOTAC Trinity RTX 4070 Ti Super', category: 'GPU', brand: 'ZOTAC', price: 79900, specs: '16GB GDDR6X / Triple Fan' },
  { id: 'gpu-4', name: 'MSI Ventus RTX 4060 Ti 8GB', category: 'GPU', brand: 'MSI', price: 38500, specs: '8GB GDDR6 / Dual Fan / Compact' },

  // Motherboards
  { id: 'mb-1', name: 'ASUS ROG MAXIMUS Z790 HERO', category: 'Motherboard', brand: 'ASUS', price: 54900, specs: 'Intel LGA1700 / DDR5 / PCIe 5.0 / Wi-Fi 6E' },
  { id: 'mb-2', name: 'MSI MAG B650 TOMAHAWK WIFI', category: 'Motherboard', brand: 'MSI', price: 21500, specs: 'AMD AM5 / DDR5 / High-speed Wi-Fi' },
  { id: 'mb-3', name: 'GIGABYTE Z790 AORUS ELITE AX', category: 'Motherboard', brand: 'GIGABYTE', price: 26500, specs: 'Intel LGA1700 / Advanced VRMs / Black' },

  // RAM
  { id: 'ram-1', name: 'G.Skill Trident Z5 RGB 32GB DDR5 6000MHz', category: 'RAM', brand: 'G.Skill', price: 12500, specs: '32GB (2x16GB) / CL30 / Aura Sync RGB' },
  { id: 'ram-2', name: 'Corsair Vengeance 16GB DDR5 5200MHz', category: 'RAM', brand: 'Corsair', price: 6200, specs: '16GB (2x8GB) / Black / Compact Profile' },
  { id: 'ram-3', name: 'Kingston Fury Beast RGB 64GB DDR5 5600MHz', category: 'RAM', brand: 'Kingston', price: 22800, specs: '64GB (2x32GB) / High-capacity / RGB' },

  // Storage
  { id: 'st-1', name: 'Samsung 990 PRO 2TB NVMe PCIe 4.0', category: 'Storage', brand: 'Samsung', price: 17500, specs: 'up to 7450 MB/s read / 2TB M.2' },
  { id: 'st-2', name: 'Crucial T500 1TB Gen4 NVMe SSD', category: 'Storage', brand: 'Crucial', price: 8200, specs: 'up to 7300 MB/s read / 1TB M.2' },
  { id: 'st-3', name: 'WD Blue 2TB SATA 3D NAND SSD', category: 'Storage', brand: 'WD', price: 11900, specs: 'SATA 2.5" / 2TB / Workload stable' },

  // Power Supplies
  { id: 'ps-1', name: 'Corsair RM1000x 1000W 80+ Gold', category: 'Power Supply', brand: 'Corsair', price: 17900, specs: '1000W / Fully Modular / Japanese Caps' },
  { id: 'ps-2', name: 'MSI MAG A850GL 850W PCIe 5.0 ATX 3.0', category: 'Power Supply', brand: 'MSI', price: 10900, specs: '850W / 80+ Gold / Modular / Native 12VHPWR' },
  { id: 'ps-3', name: 'Deepcool PF650 650W 80+ Standard', category: 'Power Supply', brand: 'Deepcool', price: 4200, specs: '650W / Non-modular / Stable' },

  // Cases
  { id: 'cs-1', name: 'Lian Li O11 Dynamic EVO (Tempered Glass)', category: 'Case', brand: 'Lian Li', price: 16900, specs: 'Mid-Tower / Modular Dual Chamber / Watercool Ready' },
  { id: 'cs-2', name: 'NZXT H9 Flow Dual Chamber High-Airflow', category: 'Case', brand: 'NZXT', price: 14500, specs: 'Mid-Tower / Seamless Glass / High Airflow' },
  { id: 'cs-3', name: 'Corsair 4000D Airflow Tempered Glass Black', category: 'Case', brand: 'Corsair', price: 8500, specs: 'Mid-Tower / Front Mesh / Sleek Profile' },

  // Coolers
  { id: 'cl-1', name: 'ASUS ROG RYUJIN III 360 ARGB Liquid Cooler', category: 'Cooler', brand: 'ASUS', price: 34500, specs: '360mm AIO / Magnetic Daisychain Fans / 3.5" LCD screen' },
  { id: 'cl-2', name: 'Deepcool LT720 360mm Liquid AIO Cooler', category: 'Cooler', brand: 'Deepcool', price: 11200, specs: '360mm AIO / Infinite Mirror Pump block / High-airflow' },
  { id: 'cl-3', name: 'Noctua NH-D15 Chromax.Black dual-tower', category: 'Cooler', brand: 'Noctua', price: 10900, specs: 'Dual tower air cooler / 2x NF-A15 140mm fans / Silent' },
];
